- name: add PostgreSQL repository
  become: true
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ OS_version.code_name }}-pgdg main
    state: present

- name: import the repository signing key
  become: true
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: install PostgreSQL
  become: true
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - postgresql-{{ db_version.major }}
    - postgresql-contrib
    - libpq-dev
    - python3-psycopg2

- name: Create GitLab & Mattermost DataBase
  become: true
  become_user: postgres
  postgresql_db:
    name: "{{ item }}"
  with_items:
    - "{{ gitlab_db.name }}"
    - "{{ mattermost_db.name }}"
