- name: install components
  become: true
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - curl
    - openssh-server
    - ca-certificates

- name: get GitLab repository installation script
  get_url:
    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
    dest: /tmp/script.deb.sh

- name: run install script
  become: true
  command: bash /tmp/script.deb.sh

- name: install GitLab
  become: true
  apt:
    name: "gitlab-ce"
    update_cache: yes
    state: latest
