- name: install NGINX
  become: true
  apt:
    name: nginx
    update_cache: yes
    state: latest

- name: Set NGINX to start at system boot
  become: true
  systemd:
    name: nginx
    enabled: true

- name: Start NGINX
  become: true
  systemd:
    name: nginx
    state: started
