- name: Add NGINX PGP key
  become: true
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present

- name: Add NGINX mainline repo into source list
  become: true
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - deb http://nginx.org/packages/mainline/ubuntu/ {{ OS_version.code_name}} nginx
    - deb-src http://nginx.org/packages/mainline/ubuntu/ {{ OS_version.code_name}} nginx

- name: install NGINX
  become: true
  apt:
    name: nginx
    update_cache: yes
    state: latest

- name: Set NGINX to start at system boot
  become: true
  systemd:
    name: nginx
    enabled: true

- name: Start NGINX
  become: true
  systemd:
    name: nginx
    state: started

- name: create nginx available & enabled sites directory
  include_tasks: createDirectory.yml
  with_items:
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled

- name: Create configuration file for Mattermost
  become: true
  template:
    src: GitLab.j2
    dest: /etc/nginx/sites-available/GitLab

- name: Create link
  become: true
  file:
    src: /etc/nginx/sites-available/GitLab
    dest: /etc/nginx/sites-enabled/GitLab
    state: link
  notify: Restart NGINX

- name: Add include configuration to nginx.conf
  become: true
  replace:
    dest: /etc/nginx/nginx.conf
    regexp: "    include /etc/nginx/conf.d/\\*.conf;"
    replace: "    include /etc/nginx/sites-enabled/*;"
  notify: Restart NGINX 
