- name: download Mattermost
  get_url:
    url: "https://releases.mattermost.com/{{ version.full }}/mattermost-team-{{ version.full }}-linux-amd64.tar.gz"
    dest: /tmp/

- name: extract the Mattermost Server files
  become: true
  unarchive:
    src: /tmp/mattermost-team-{{ version.full }}-linux-amd64.tar.gz
    dest: /opt/
    copy: no

- name: create Mattermost group
  become: true
  group:
    name: "{{ user.group }}"
    state: present
    system: yes

- name: create the storage directory for files
  become: true
  file:
    path: /opt/mattermost/data
    state: directory
